In [3]:

import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"  # Enable verbose logs
print("Starting TensorFlow import...")
import tensorflow as tf
print("TensorFlow imported successfully.")

Starting TensorFlow import...
TensorFlow imported successfully.


In [4]:
hello = tf.constant('Hello World')


In [5]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [6]:
x = tf.constant(100)

In [7]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [8]:
a = tf.constant(5)
b = tf.constant(3)
c = a + b
print(c)

tf.Tensor(8, shape=(), dtype=int32)


In [9]:
x = tf.constant(2)
y = tf.constant(3)

print(x+y)

tf.Tensor(5, shape=(), dtype=int32)


In [10]:
print('Operations with Constants')
print('Addition',x+y)
print('Subtraction',x-y)
print('Multiplication',x*y)
print('Division',x/y)

Operations with Constants
Addition tf.Tensor(5, shape=(), dtype=int32)
Subtraction tf.Tensor(-1, shape=(), dtype=int32)
Multiplication tf.Tensor(6, shape=(), dtype=int32)
Division tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


In [11]:
x = tf.Variable(0, dtype=tf.int32)  # Use tf.Variable instead of tf.placeholder
y = tf.Variable(0, dtype=tf.int32)

In [12]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)

In [13]:
d = {x.ref(): 20, y.ref(): 30}  # Using ref() for compatibility


In [15]:

import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [16]:
a

array([[5., 5.]])

In [17]:
a.shape

(1, 2)

In [18]:
b

array([[2.],
       [2.]])

In [19]:
b.shape

(2, 1)

In [20]:

mat1 = tf.constant([[1, 2], [3, 4]])  # Shape: (2,2)
mat2 = tf.constant([[5], [6]])        # Shape: (2,1)

# Perform matrix multiplication
matrix_multi = tf.matmul(mat1, mat2)

# Print the result
print(matrix_multi.numpy())

[[17]
 [39]]


In [21]:

result = matrix_multi
print(result)

tf.Tensor(
[[17]
 [39]], shape=(2, 1), dtype=int32)
